#!/bin/bash
# Auto-detect cluster configuration and update params.env files
# Usage: ./scripts/obtain-cluster-config.sh
#
# Note: deploy.sh sources this automatically. Run standalone to regenerate
# configuration without deploying.
#
# Detects:
# - Cluster domain (for gateway hostnames)
# - TLS secret (for HTTPS)
#
# Updates:
# - params.env (root)
# - manifests/gateways/params.env
# - manifests/keycloak/params.env

set -e

_OCC_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_OCC_PROJECT_DIR="$(dirname "$_OCC_SCRIPT_DIR")"

# ============================================
# Configuration function (reusable)
# ============================================
configure_cluster() {
    local quiet="${1:-false}"
    
    [[ "$quiet" != "true" ]] && echo "Detecting cluster configuration..."

    # Detect cluster domain
    CLUSTER_DOMAIN=$(kubectl get ingresses.config.openshift.io cluster -o jsonpath='{.spec.domain}' 2>/dev/null || echo "")
    if [ -z "$CLUSTER_DOMAIN" ]; then
        echo "❌ Could not detect cluster domain"
        return 1
    fi
    [[ "$quiet" != "true" ]] && echo "   Cluster domain: ${CLUSTER_DOMAIN}"

    # Detect TLS secret
    TLS_SECRET=$(kubectl get secrets -n openshift-ingress -o name 2>/dev/null | grep -E 'cert-bundle-secret$' | head -1 | sed 's/secret\///' || echo "")
    if [ -z "$TLS_SECRET" ]; then
        [[ "$quiet" != "true" ]] && echo "   ⚠️  No TLS secret found"
        TLS_SECRET="placeholder-tls-secret"
    else
        [[ "$quiet" != "true" ]] && echo "   TLS secret: ${TLS_SECRET}"
    fi

    # Generate hostnames (exported for use by caller)
    export CLUSTER_DOMAIN TLS_SECRET
    export KEYCLOAK_HOST="keycloak.${CLUSTER_DOMAIN}"
    export TENANT_A_HOST="tenant-a.${CLUSTER_DOMAIN}"
    export TENANT_B_HOST="tenant-b.${CLUSTER_DOMAIN}"

    # Write root params.env (cluster-wide config)
    cat > "$_OCC_PROJECT_DIR/params.env" << EOF
# Cluster configuration - generated $(date)
cluster-domain=${CLUSTER_DOMAIN}
tls-secret-name=${TLS_SECRET}
keycloak-hostname=${KEYCLOAK_HOST}
tenant-a-hostname=${TENANT_A_HOST}
tenant-b-hostname=${TENANT_B_HOST}
EOF

    # Write gateways params.env (external hostnames for ingress)
    cat > "$_OCC_PROJECT_DIR/manifests/gateways/params.env" << EOF
# Generated by scripts/obtain-cluster-config.sh - $(date)
tls-secret-name=${TLS_SECRET}
keycloak-hostname=${KEYCLOAK_HOST}
tenant-a-hostname=${TENANT_A_HOST}
tenant-b-hostname=${TENANT_B_HOST}
EOF

    # Write keycloak params.env (external hostname for Keycloak ingress)
    cat > "$_OCC_PROJECT_DIR/manifests/keycloak/params.env" << EOF
# Generated by scripts/obtain-cluster-config.sh - $(date)
keycloak-hostname=${KEYCLOAK_HOST}
EOF

    [[ "$quiet" != "true" ]] && echo "   ✅ Configuration updated"
    return 0
}

# ============================================
# Run if executed directly (not sourced)
# ============================================
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    configure_cluster
    echo ""
    echo "Files updated:"
    echo "   params.env"
    echo "   manifests/gateways/params.env"
    echo "   manifests/keycloak/params.env"
    echo ""
    echo "To deploy tenants:"
    echo "   kubectl apply -f manifests/tenants/tenant-a/modelsasservice.yaml"
    echo "   kubectl apply -f manifests/tenants/tenant-a/tier-mapping-configmap.yaml"
    echo ""
    echo "Note: Gateways and Keycloak use Kustomize (kubectl apply -k)"
fi
